### ISSUE TITLE
Create Theme

### ISSUE THREAD

**Issue by anandisrocking007** [Brackets-Themes/DarkSoda#6]
Hello sir i was thinking of creating a new theme for myself but i can not find where can you see all the CSS selectors required for creating the the theme such as .cm-keyword, .cm-qualifier, .cm-builtin or .cm-tag,some themes have more string than even the default brackets theme i cant understand where do you get these.....i know this is the wrong place to write this but i don't know anywhere else to write it..........any help would be appreciated.

**Comment by MiguelCastillo** [comment]
Hi!  I dont think there is a standard list of selector you need to modify. You modify based on your own needs.  The way I approach the problem is by inspecting in the the developer tools the parts of the editor I am looking to customize and write selectors for that.

Either way, this is a boilerplacte project I use for getting started which might help you as well.  https://github.com/Brackets-Themes/BoilerPlate

Feel free to ask questions here :)

**Comment by anandisrocking007** [comment]
Thank you
